### PR TITLE
Add a test to compare negative numbers

### PR DESCRIPTION
**Pull request by eg15**
Looks like I found a bug.
"-1000000000 < -1" returns 0 (false) on my machine which is obviously wrong.
The fix will follow.

### CODE REVIEW

**Comment by gavinhoward** [comment]
Yes, you did find a bug.

Your fix looks great, and your tests do as well. I just have two requests:

1. Move your tests and results into files called `comp.txt` and `comp_results.txt`.
2. Change the name in `tests/bc/all.txt`.

I want you to do this because I am going to write a more comprehensive set of tests for comparisons in general to make sure I did not miss anything else.

If you don't have the time to do this, I could always pull it and do the change myself.

**Comment by eg15** [comment]
Just finished, thank you.

BTW it looks like busybox guys took your code and kept the bug in their modified version.
Just fixed it there as well: https://bugs.busybox.net/show_bug.cgi?id=12336

Then it should be fixed in Alpine (that's where I encountered it this morning).

**Comment by gavinhoward** [comment]
`busybox` didn't exactly take my code; I gave them my code, when it had a lot more bugs as well. Unfortunately, they decided to go their own way with it, so I don't really contribute back. (They added even more bugs.)

I will merge this when I get home from work. I should have a release out after testing, which could take up to a week. I don't expect this to take that long to test, since it's so small, but I may find other problems.

**Comment by gavinhoward** [comment]
I pulled manually. Thank you for your help!

**Pull request merged**
