### PR TITLE
lexer: optimize grouping of keyword properties

### PR DESCRIPTION
**Pull request by rofl0r**
1) less size in .text used
2) less code
3) properties are grouped together, so there's no need for comments

### CODE REVIEW

**Comment by gavinhoward** [comment]
Thank you for the ideas! I will use them, though I need to change a lot to fit with the current style. Because of that, I will close this PR.

**Comment by rofl0r** [comment]
this patch makes it also "better for toybox":
previous code used 20*4 byte for the lengths, 20*4 bytes for the posix array, 20*8 for the pointers to string, and another ca 20*7 bytes for the strings themselves, while my approach uses 11*20 bytes.

**Comment by rofl0r** [comment]
i can also use "true" over "1" if you prefer.

**Comment by gavinhoward** [comment]
I will go ahead and make the changes after merge.

**Comment by rofl0r** [comment]
thanks! exciting project, keep on the good work :+1:
i hope it will be possible to use standalone (without toybox), so i can integrate it into sabotage linux.

**Comment by gavinhoward** [comment]
Yes, it will be standalone. I made that decision early on.
I am also looking to get it into busybox.

**Comment by gavinhoward** [comment]
@rofl0r I realized that I need to ask a few questions.

First, because I want this bc in toybox, busybox, and Linux distros, I would like to be able to license it under whatever license would be most convenient for those projects. (This is to prevent [license proliferation](https://en.wikipedia.org/wiki/License_proliferation) problems because GPL and most BSD licenses are incompatible.) That means I need permission from all copyright holders to license the code however I wish.

So, if you would please reply, to my email or with a comment, with the below text and your name:

> I grant Gavin Howard permission to license bc, including any of my own contributions, under whatever license he wishes and to relicense it for specific projects as long as the source code for those projects is publicly available (open).
> Signed <your_name>

If you don't wish to grant permission, I can just pull your code out.

Also, if you do grant permission, I need to give you credit in the NOTICE.md file. Please let me know what name you wish to be referred by. (Your username will work if you wish.) If you would like your email on there, you can send that too.

Thank you!

**Comment by rofl0r** [comment]
I grant Gavin Howard permission to license bc, including any of my own contributions, under whatever license he wishes and to relicense it for specific projects as long as the source code for those projects is publicly available (open).
Signed rofl0r

**Comment by rofl0r** [comment]
i don't need any attribution or credits...

**Comment by gavinhoward** [comment]
Okay. Thank you!

For my own sake (to remember all who have helped me), I will probably still put your username in the notice file.

**Pull request merged**
